---
- name: Copy website folder into image
  hosts: all
  tasks:
    - name: Add website folder
      synchronize:
        src: /path/to/website/folder 
        dest: /root
        recursive: yes
        rsync_opts:
          - "--no-motd"
